---
# tasks file for ansible-role-nis
#
- name: does the var/yp/sitename exist
  stat: path=/var/yp/{{ nis_domain }} 
  register: yppath

- debug: msg="nis_domain already initialized"
  when: yppath.stat.isdir is defined and yppath.stat.isdir

- name: initialize the master nis server
  command: ypinit -m {{ ansible_fqdn }}
  when: nis_server and nis_initialize and not yppath.stat.isdir

- name: do not export shadow hashes by setting MERGE_PASSWD=false in /var/yp/Makefile
  lineinfile: dest=/var/yp/Makefile state=present regexp='^MERGE_PASSWD=true' line='MERGE_PASSWORD=false' validate='cd /var/yp; make' backup=yes
  when: nis_server and nis_initialize
