---
# tasks file for ansible-role-nis

- name: template in yp.conf on non-servers
  template: src=yp.conf.j2 dest=/etc/yp.conf
  when: not nis_server
  notify: 
    - restart rpcbind
    - restart ypbind

- name: install nis server packages
  yum: name={{ item }} state=latest
  with_items: nis_server_packages
  when: nis_server
  notify:
    - restart rpcbind
    - restart ypbind

- name: install nis common packages 
  yum: name={{ item }} state=latest
  with_items: nis_packages
  notify:
    - restart ypbind
  
- name : template in nsswitch - conditionals inside template
  template: src=nsswitch.conf.j2 dest=/etc/nsswitch.conf
  notify:
    - restart rpcbind 
    - restart ypbind

- name: add NISDOMAIN to sysconfig/network
  lineinfile: dest=/etc/sysconfig/network line="NISDOMAIN="{{ nis_domain }}"" backup=yes insertbefore=BOF
  notify:
    - restart rpcbind 
    - restart ypbind

- name: enable ypbind
  service: name=ypbind enabled=yes

- name: enable rhel-domainname 
  service: rhel-domainname enabled=yes
