---
# handlers file for ansible-role-nis

- name: restart rpcbind
  service: name=rpcbind state=restarted

- name: restart ypbind
  service: name=ypbind state=restarted
  when: not nis_server

- name: restart ypserv
  service: name=ypserv state=restarted
  when: nis_server

- name: ypmake
  command: make all chdir=/var/yp
  when: nis_server
